'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Convertor.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property app_icon() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("app_icon", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert.
        '''</summary>
        Friend ReadOnly Property btnConvert_Convert() As String
            Get
                Return ResourceManager.GetString("btnConvert_Convert", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop.
        '''</summary>
        Friend ReadOnly Property btnConvert_Stop() As String
            Get
                Return ResourceManager.GetString("btnConvert_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Convert All.
        '''</summary>
        Friend ReadOnly Property btnConvertAll_Convert_All() As String
            Get
                Return ResourceManager.GetString("btnConvertAll_Convert_All", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Completed Successfully.
        '''</summary>
        Friend ReadOnly Property BWMain_Completed_Successfully() As String
            Get
                Return ResourceManager.GetString("BWMain_Completed_Successfully", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error : .
        '''</summary>
        Friend ReadOnly Property BWMain_DoWork_Error___() As String
            Get
                Return ResourceManager.GetString("BWMain_DoWork_Error___", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stopped.
        '''</summary>
        Friend ReadOnly Property BWMain_Stopped() As String
            Get
                Return ResourceManager.GetString("BWMain_Stopped", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend ReadOnly Property ItemsList__Error() As String
            Get
                Return ResourceManager.GetString("ItemsList__Error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Duplicated files are not allowed in list.
        '''</summary>
        Friend ReadOnly Property ItemsList_Duplicated_files_are_not_allowed_in_list() As String
            Get
                Return ResourceManager.GetString("ItemsList_Duplicated_files_are_not_allowed_in_list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File Does not exist.
        '''</summary>
        Friend ReadOnly Property ItemsList_files_Does_Not_Exist() As String
            Get
                Return ResourceManager.GetString("ItemsList_files_Does_Not_Exist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Please select mkv or mp4 file.
        '''</summary>
        Friend ReadOnly Property NotSupported() As String
            Get
                Return ResourceManager.GetString("NotSupported", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
